=== Denisprkh/JWD_XML_Parser/testData/touristVouchersTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/touristVouchersTest"
        xmlns:tns="http://www.example.com/touristVouchersTest"
        elementFormDefault="qualified">
    <element name="tourist_vouchers">
        <complexType>
            <sequence>
                <element name="tourist_voucher"
                         type="tns:Tourist_Voucher"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Tourist_Voucher">
        <sequence>
            <element name="voucher_type" type="tns:Voucher_Type"/>
            <element name="country" type="tns:Country"/>
            <element name="city" type="tns:City"/>
            <element name="duration" type="tns:Duration"/>
            <element name="transport" type="tns:Transport"/>
            <element name="hotel_characteristics" type="tns:Hotel_Characteristics"/>
            <element name="cost" type="decimal"/>
        </sequence>
        <attribute name="id" type="tns:id" use="required"/>
        <attribute name="title" type="string" use="optional" default="Tourist voucher"/>
    </complexType>

    <simpleType name="City">
        <restriction base="string">
            <pattern value="[a-zA-Z]{1,25}"/>
        </restriction>
    </simpleType>

    <simpleType name="Country">
        <restriction base="string">
            <pattern value="[a-zA-Z]+"/>
        </restriction>
    </simpleType>

    <simpleType name="id">
        <restriction base="ID">
            <pattern value="ID\d{1,20}"/>
        </restriction>
    </simpleType>

    <simpleType name="Voucher_Type">
        <restriction base="string">
            <enumeration value="weekend"/>
            <enumeration value="excursion"/>
            <enumeration value="relaxation"/>
            <enumeration value="pilgrimage"/>
            <enumeration value="cruise"/>
        </restriction>
    </simpleType>

    <simpleType name="Transport">
        <restriction base="string">
            <enumeration value="plane"/>
            <enumeration value="ship"/>
            <enumeration value="bus"/>
            <enumeration value="train"/>
        </restriction>
    </simpleType>


    <complexType name="Hotel_Characteristics">
        <sequence>
            <element name="stars" type="tns:Stars"/>
            <element name="food_type" type="tns:Food_Type"/>
            <element name="room_type" type="tns:Room_Type"/>
            <element name="tv" type="boolean"/>
            <element name="air_condition" type="boolean"/>
        </sequence>
    </complexType>

    <simpleType name="Stars">
        <restriction base="int">
            <pattern value="[1-5]"/>
        </restriction>
    </simpleType>

    <simpleType name="Food_Type">
        <restriction base="string">
            <enumeration value="OB"/>
            <enumeration value="BB"/>
            <enumeration value="HB"/>
            <enumeration value="FB"/>
            <enumeration value="AL"/>
        </restriction>
    </simpleType>

    <simpleType name="Room_Type">
        <restriction base="string">
            <enumeration value="SGL"/>
            <enumeration value="DBL"/>
            <enumeration value="TRPL"/>
            <enumeration value="Suite"/>
            <enumeration value="ExB"/>
        </restriction>
    </simpleType>

    <complexType name="Duration">
        <sequence>
            <element name="start_date" type="date"/>
            <element name="end_date" type="date"/>
        </sequence>
    </complexType>

</schema>

=== Denisprkh/JWD_XML_Parser/testData/touristVouchersTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tourist_vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns="http://www.example.com/touristVouchersTest"
                  xsi:schemaLocation="http://www.example.com/touristVouchers touristVouchersTest.xsd">
    <tourist_voucher id="ID1">
        <voucher_type>excursion</voucher_type>
        <country>Germany</country>
        <city>Berlin</city>
        <duration>
            <start_date>2020-05-19</start_date>
            <end_date>2020-05-29</end_date>
        </duration>
        <transport>plane</transport>
        <hotel_characteristics>
            <stars>4</stars>
            <food_type>AL</food_type>
            <room_type>DBL</room_type>
            <tv>true</tv>
            <air_condition>true</air_condition>
        </hotel_characteristics>
        <cost>2000.00</cost>
    </tourist_voucher>
</tourist_vouchers>
